# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/images'
    thumbnails_directory: '%kernel.project_dir%/public/uploads/thumbnails'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    # Image Upload Service
    App\Service\ImageUploadService:
        arguments:
            $uploadDirectory: '%uploads_directory%'
            $thumbnailDirectory: '%thumbnails_directory%'

    # Page Template Service
    App\Service\PageTemplateService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Login Success Handler
    App\Security\LoginSuccessHandler:
        arguments:
            $urlGenerator: '@router'

    # Push Notification Service
    App\Service\PushNotificationService:
        arguments:
            $vapidPublicKey: '%env(VAPID_PUBLIC_KEY)%'
            $vapidPrivateKey: '%env(VAPID_PRIVATE_KEY)%'
            $vapidSubject: '%env(VAPID_SUBJECT)%'

    # Twig Extension for VAPID Public Key
    App\Twig\VapidExtension:
        arguments:
            $vapidPublicKey: '%env(VAPID_PUBLIC_KEY)%'
        tags: ['twig.extension']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
